# remote_theme: niklasbuschmann/contrast@v2.11
remote_theme: cotes2020/jekyll-theme-chirpy@v5.2.1
plugins:
  - jekyll-remote-theme
title: "Estudiando DAW"
author: "Sergio (s-moreno"
description: "Página personal de Desarrollo de aplicaciones web"
permalink: /:title/
lang: "es"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: true        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: false        # show a sidebar instead of the usual header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {file: "index.md"}
  - {file: "tareas.md"}

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Mail, icon: envelope, url: "mailto:smoreno@birt.eus"}
  - {title: Github, icon: github, url: "https://github.com/s-moreno"}
  - {title: Subscribe, icon: rss, url: "/feed.xml"}

comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
