# remote_theme: niklasbuschmann/contrast@v2.11
remote_theme: bitbrain/jekyll-dash
plugins:
  - jekyll-remote-theme

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  #avatar_source: github
  #github_username: s-moreno
  #avatar_source: local
  #avatar_path: /assets/avatar.png

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://twitter.com/s-moreno
      icon: twitter-square
      color: cyan
  
  # wether the author box should be displayed or not
  show_author: true
