title: Sergio
author: s-moreno
email: smoreno@birt.eus
description: > # this means to ignore newlines until "show_exerpts:"
  Me llamo Sergio y estoy estudiando Desarrollo de aplicaciones web (DAW) en BirtLH.
  Aquí iré subiendo ciertas Tareas para los módulos del ciclo.
show_excerpts: false # set to true to show excerpts on the homepage


remote_theme: bitbrain/jekyll-dash
plugins:
  - jekyll-remote-theme
  - jekyll-paginate

# jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"

dash:
  # the way how dates should be displayed
  date_format: "%b %-d, %Y"

  # the animation speed of the post scroll-in effect
  animation_speed: 50

  # wether to enable Right-to-Left support or not
  rtl: false

  # Replaces the default avatar provider (gravatar)
  avatar_source: github
  github_username: s-moreno
  avatar_source: local
  avatar_path: /assets/avatar.png

  # generate social links in footer
  # supported colors: green, red, orange, blue, cyan, pink, teal, yellow, indigo, purple
  social_links:
    - url: https://github.com/s-moreno
      icon: github-square
      color: purple
  
  # wether the author box should be displayed or not
  show_author: true
